name: helpful_flutter_tools
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  # NOTE: Necessary
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0
  # NOTE: State Management
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.1
  flutter_bloc: ^8.1.1
  # NOTE: Router
  auto_route: ^5.0.4
  # NOTE: Speed up development process
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: null
  auto_route_generator: null

flutter:

  uses-material-design: true
  assets:
    - assets/data/